spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  application:
    name: project
  data:
    redis:
      host: redis
      port: 6379
      timeout: 6000


  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
    api-docs:
      path: /v3/api-docs
      title: ShoppingMall API
      description: ShoppingMall
      version: 1.0.0

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://tomdb:3306/hotel
    username: root
    password: 2846

  jpa:
    hibernate:
      ddl-auto: update
      #ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  shutdown: graceful
  port: 33000
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  error:
    include-stacktrace: always #에러 로그 always, never
    include-message: always

jwt:
  secret: "jwtsecretkeyjwtsecretkeyjwtsecretkey12"